In [1]:
print("Hello World")






Hello World


In [3]:
import numpy as np
print(np.array([1]))


ModuleNotFoundError: No module named 'numpy'

In [5]:
import numpy as a
print(a.array([1]))

ModuleNotFoundError: No module named 'numpy'

In [1]:
import numpy as np
print(np.array([1]))

[1]


In [2]:
import numpy as np
print(np.__version__)

2.4.6


In [3]:
import numpy as a
print(a.array([1]))

[1]


In [16]:
arr1= np.array([1,2,3,4,5,6])
arr2= np.array([1,2,3,4,5], dtype=float)
arr3= np.array(range(4))
arr4= np.array(([1,2],[3,4]))
arr5= np.arange(6)
print(arr1,arr2,arr3,arr4,"\n",arr5)

[1 2 3 4 5 6] [1. 2. 3. 4. 5.] [0 1 2 3] [[1 2]
 [3 4]] 
 [0 1 2 3 4 5]


In [17]:

arr = np.array(["apple", "baaanana", "cherry"])
print(arr)          # ['apple' 'banana' 'cherry']
print(arr.dtype)    # <U6  (Unicode string of max length 6)

['apple' 'baaanana' 'cherry']
<U8


In [18]:
type(arr1)
arr1.dtype
arr4.shape

arr6 = arr5.reshape(3, 2)
print(arr6)

arr6_f = arr5.reshape(3, 2, order='F')
print(arr6_f)

[[0 1]
 [2 3]
 [4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [20]:
arr= np.array([[1,2,4],[7,13,21]])
print(arr,arr.shape)

[[ 1  2  4]
 [ 7 13 21]] (2, 3)


In [25]:
# < START >
# Initialize an array ZERO_ARR of dimensions (4, 5, 2) whose every element is 0
ZERO_ARR= np.zeros((4,5,2))
# < END >

print(ZERO_ARR)

# < START >
# Initialize an array ONE_ARR of dimensions (4, 5, 2) whose every element is 1
ONE_ARR= np.ones((4,5,2))
# < END >

print(ONE_ARR)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [28]:
y = np.array([[1, 2, 3],
              [4, 5, 6]])

# < START >
# Create a new array y_transpose that is the transpose of matrix y
y_transpose= y.reshape(3,2,)
print(y_transpose)
# < END >


[[1 2]
 [3 4]
 [5 6]]


In [29]:
y = np.array([[1, 2, 3],
              [4, 5, 6]])

# < START >
# Create a new array y_transpose that is the transpose of matrix y
y_transpose= y.T
# < END >

print(y_transpose)

# < START >
# Create a new array y_flat that contains the same elements as y but has been flattened to a column array
y_flat= y.reshape(-1,1)
# < END >

print(y_flat)

[[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [31]:
# < START >
# Initialize an array ZERO_ARR of dimensions (4, 5, 2) whose every element is 0
ZERO_ARR= np.zeros((4,5,2))
# < END >

print(ZERO_ARR)

# < START >
# Initialize an array ONE_ARR of dimensions (4, 5, 2) whose every element is 1
ONE_ARR= np.ones((4,5,2))
# < END >

print(ONE_ARR)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [36]:
arr1= np.arange(1,11).reshape(2,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [37]:
# <START>
# Initialize the column matrix here
x = np.array([[1, 2, 3],
              [4, 5, 6]])
a= np.array([4,7,11])
y= a.reshape(3,1)
# <END>

assert y.shape == (3, 1)
# The above line is an assert statement, which halts the program if the given condition evaluates to False.
# Assert statements are frequently used in neural network programs to ensure our matrices are of the right dimensions.

print(y)

# <START>
# Multiply both the arrays here
z= x@y
# <END>

assert z.shape == (2, 1)

print(z)

[[ 4]
 [ 7]
 [11]]
[[ 51]
 [117]]


In [38]:
x = np.array([4, 1, 5, 6, 11])

# <START>
# Create a new array y with the middle 3 elements of x
y= x[1:4]
# <END>

print(y)

[1 5 6]


In [39]:
z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# <START>
# Create a new array w with alternating elements of z
w= z[0:10:2]
# <END>

print(w)

[1 3 5 7 9]


In [41]:
arr_2d = np.array([[4, 5, 2],
          [3, 7, 9],
          [1, 4, 5],
          [6, 6, 1]])

# <START>
# Create a 2D array sliced_arr_2d that is of the form [[5, 2], [7, 9], [4, 5]]
sliced_arr_2d= arr_2d[0:3,1:3]
# <END>

print(sliced_arr_2d)

[[5 2]
 [7 9]
 [4 5]]


In [45]:
arr1= np.arange(1,11)
print(arr1)
print(arr1[0:5])
print(arr1[0:4])
print(arr1[0:4:1])
print(arr1[0:4:2])
print(arr1[::-2])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]
[1 2 3 4]
[1 2 3 4]
[1 3]
[10  8  6  4  2]


In [48]:
arr = np.arange(6).reshape(3,2)
print(arr)

new_arr = arr
print(new_arr)

new_arr[2] = 100          # Here we are changing a value in new_arr only,  but ...

print(arr)
print(new_arr)

[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[  0   1]
 [  2   3]
 [100 100]]
[[  0   1]
 [  2   3]
 [100 100]]


In [49]:
arr1 = np.array([1, 2, 3, 4])
b = 1

# <START>
# Implement broadcasting to add b to each element of arr1
arr1 = arr1+3
# <END>

print(arr1)

[4 5 6 7]


In [50]:

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr3 = np.array([[4],[5]])

# <START>
# Multiply each element of the first row of arr2 by 4 and each element of the second row by 5, using only arr2 and arr3
arr2 = arr2*arr3
# <END>

print(arr2)

[[ 4  8 12]
 [20 25 30]]


In [52]:
arr1 = np.arange(4)
arr2 = arr1 + 3
print(arr1)
print(arr2)

print(np.dot(arr1, arr2))
print(arr1*arr2)

[0 1 2 3]
[3 4 5 6]
32
[ 0  4 10 18]


In [53]:
arr1 = np.arange(6).reshape(3,2)
arr2 = np.ones((2,3))
print(arr1,"\n-----")
print(arr2,"\n-----")

# The following lines are all equivalent, they all calculate the dot product of the two arrays
print(np.dot(arr1,arr2),"\n-----")
print(arr1.dot(arr2),"\n-----")
print(arr1 @ arr2)
# What happens when the following code is run?
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(12).reshape(4,3)
print(arr1,"\n-----")
print(arr2,"\n-----")
print(arr1 @ arr2)

[[0 1]
 [2 3]
 [4 5]] 
-----
[[1. 1. 1.]
 [1. 1. 1.]] 
-----
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]] 
-----
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]] 
-----
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]
[[0 1 2]
 [3 4 5]] 
-----
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
-----


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [56]:
arr1 = np.arange(6).reshape(3,2)
arr2 = np.ones((2,3))
print(arr1,"\n-----")
print(arr2,"\n-----")

# The following lines are all equivalent, they all calculate the dot product of the two arrays
print(np.dot(arr1,arr2),"\n-----")
print(arr1.dot(arr2),"\n-----")
print(arr1 @ arr2)

[[0 1]
 [2 3]
 [4 5]] 
-----
[[1. 1. 1.]
 [1. 1. 1.]] 
-----
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]] 
-----
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]] 
-----
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]


In [57]:
arr1 = np.arange(9).reshape(3,3)
print(arr1,"\n-----")
print(np.linalg.det(arr1))

[[0 1 2]
 [3 4 5]
 [6 7 8]] 
-----
0.0


In [58]:
# Now let's find out the eigen values and vectors of the matrix

mat = np.arange(1,10).reshape(3,3)
eigen_value, eigen_vector = np.linalg.eig(mat)

print(f"Eigen values are {eigen_value}")
print(f"Eigen vectors are \n {eigen_vector}")

Eigen values are [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigen vectors are 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [59]:
arr1 = np.arange(6).reshape(3, 2)
arr2 = np.ones((2, 3))
print(np.dot(arr1, arr2))
print(arr1.dot(arr2))
print(arr1 @ arr2)

[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]


In [60]:
arr = np.arange(8)
print(arr > 5)
print(np.any(arr > 5))
print(np.all(arr > 5))
print(arr[arr > 5])


[False False False False False False  True  True]
True
False
[6 7]


In [64]:
import time

arr_nonvectorized = np.random.rand(1000, 1000)
arr_vectorized = np.array(arr_nonvectorized) # making a deep copy of the array

start_nv = time.time()

# Non-vectorized approach
# <START>
for i in range(arr_nonvectorized.shape[0]):
    for j in range(arr_nonvectorized.shape[1]):
        arr_nonvectorized[i][j]= arr_nonvectorized[i][j]*3


# <END>

end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000*(end_nv-start_nv), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
print(arr_nonvectorized)

start_v = time.time()

# Vectorized approach
# <START>
arr_vectorized= arr_vectorized*3
# <END>

end_v = time.time()
print("Time taken in vectorized approach:", 1000*(end_v-start_v), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
print(arr_vectorized)

Time taken in non-vectorized approach: 1272.7150917053223 ms
[[7.04511677e-01 6.18313212e-01 2.43539145e-01 ... 1.07123113e+00
  2.26495445e+00 1.32406962e+00]
 [1.91494291e+00 6.99127885e-01 2.13164952e+00 ... 5.19151227e-01
  2.54395223e+00 7.18986959e-01]
 [2.04775222e+00 9.08977005e-01 1.47280627e+00 ... 1.82408819e-01
  9.58499636e-01 6.88328740e-04]
 ...
 [4.37222711e-01 4.84460952e-01 2.80015825e+00 ... 1.11764336e+00
  8.11600486e-01 6.44869022e-01]
 [1.84094134e+00 1.88752975e+00 4.38907858e-01 ... 2.33411229e+00
  4.48872487e-01 2.65934183e+00]
 [2.21764924e+00 9.79609856e-02 1.42476704e+00 ... 7.91362795e-02
  7.61058040e-01 2.73311975e+00]]
Time taken in vectorized approach: 4.39763069152832 ms
[[7.04511677e-01 6.18313212e-01 2.43539145e-01 ... 1.07123113e+00
  2.26495445e+00 1.32406962e+00]
 [1.91494291e+00 6.99127885e-01 2.13164952e+00 ... 5.19151227e-01
  2.54395223e+00 7.18986959e-01]
 [2.04775222e+00 9.08977005e-01 1.47280627e+00 ... 1.82408819e-01
  9.58499636e-01 6.8